/**
 * Formatting utilities — pure functions for display formatting.
 * No business logic, no API calls.
 */

import { AnalysisResponse } from "@/lib/types";
import { POINTS, CAPS } from "./constants";

export function formatTimestamp(timestamp: number): string {
  if (!timestamp) return "Unknown date";
  return new Date(timestamp * 1000).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export function shortAddress(address: string, chars = 4): string {
  if (!address || address.length < 10) return address;
  return `${address.slice(0, chars + 2)}...${address.slice(-chars)}`;
}

export function shortHash(hash: string, chars = 6): string {
  if (!hash || hash.length < 10) return hash;
  return `${hash.slice(0, chars + 2)}...`;
}

/**
 * Generates a plain-text off-chain report for download.
 */
export function generateTextReport(
  analysis: AnalysisResponse,
  includesENS: boolean
): string {
  const date = new Date(analysis.analyzedAt * 1000).toUTCString();
  const { profile, contracts, ens } = analysis;
  const { breakdown, summary } = profile;

  const lines: string[] = [
    "═══════════════════════════════════════════════════════",
    "  PROOF OF DEV — ON-CHAIN ACTIVITY PROFILE",
    "═══════════════════════════════════════════════════════",
    "",
    "⚠  DISCLAIMER",
    "   This profile reflects on-chain activity only.",
    "   It does NOT measure developer skill or code quality.",
    "   Data may be incomplete depending on API availability.",
    "",
    "─── WALLET ─────────────────────────────────────────────",
    `   Address:   ${analysis.address}`,
    includesENS && ens.name ? `   ENS Name:  ${ens.name}` : "   ENS Name:  Not included",
    `   Analyzed:  ${date}`,
    "",
    "─── ACTIVITY SUMMARY ───────────────────────────────────",
    `   Contracts Deployed:  ${summary.contractCount}${profile.cappedAt ? ` (scored up to ${profile.cappedAt})` : ""}`,
    `   Verified Contracts:  ${summary.verifiedContractCount}`,
    includesENS
      ? `   ENS Status:         ${ens.name ? `Yes (${ens.name})` : "No ENS name found"}`
      : "   ENS Status:         Not included",
    "",
    "─── REPUTATION SCORE ───────────────────────────────────",
    `   Total Score:  ${profile.score}`,
    `   Tier:         ${summary.tier} — ${summary.tierDescription}`,
    "",
    "   Breakdown:",
    `     Contract Deployments:  +${breakdown.contractDeployments}`,
    `       (${POINTS.CONTRACT_DEPLOYMENT} pts each, capped at ${CAPS.MAX_DEPLOYMENTS_SCORED})`,
    `     Verified Contracts:    +${breakdown.verifiedContracts}`,
    `       (${POINTS.VERIFIED_CONTRACT} pts each, capped at ${CAPS.MAX_VERIFIED_SCORED})`,
    `     ENS Ownership:         +${breakdown.ensOwnership}`,
    `     ENS Metadata:          +${breakdown.ensMetadata}`,
    `     Time Weight Adj:       ${breakdown.timeMultiplierBonus >= 0 ? "+" : ""}${breakdown.timeMultiplierBonus}`,
    `       (>30 days = 1.2×, <30 days = 0.8×, burst = additional 0.8×)`,
    "",
    "─── EXPLANATIONS ───────────────────────────────────────",
    ...profile.explanations.map((e) => `   • ${e}`),
    "",
    "─── SCORING RULES ──────────────────────────────────────",
    `   +${POINTS.CONTRACT_DEPLOYMENT}  per contract deployment (max ${CAPS.MAX_DEPLOYMENTS_SCORED})`,
    `   +${POINTS.VERIFIED_CONTRACT}  per verified contract (max ${CAPS.MAX_VERIFIED_SCORED})`,
    `   +${POINTS.ENS_OWNERSHIP}   ENS name ownership`,
    `   +${POINTS.ENS_METADATA}   per ENS metadata field (avatar, url, github)`,
    "   Time: 1.2× if >30 days old · 0.8× if <30 days · 0.8× burst penalty",
    "",
  ];

  if (contracts.length > 0) {
    lines.push("─── DEPLOYED CONTRACTS ─────────────────────────────────");
    contracts.forEach((c, i) => {
      lines.push(`   ${i + 1}. ${c.contractAddress}`);
      lines.push(`      Deployed: ${formatTimestamp(c.timestamp)}`);
      lines.push(`      Verified: ${c.isVerified ? "Yes" : "No"}`);
      lines.push(`      Tx: ${c.transactionHash}`);
      if (i < contracts.length - 1) lines.push("");
    });
    lines.push("");
  }

  lines.push("═══════════════════════════════════════════════════════");
  lines.push("  Generated by Proof of Dev · proof-of-dev.vercel.app");
  lines.push("═══════════════════════════════════════════════════════");

  return lines.join("\n");
}
